#ifndef INTERRUPTS_H
#define INTERRUPTS_H

#define PRIORITY_KEYBOARD_INTERRUPT 4
#define PRIORITY_SERIAL_INTERRUPT   5
#define PRIORITY_STORAGE_INTERRUPT  5
#define PRIORITY_AUDIO_INTERRUPT    2
#define PRIORITY_TIMEOUT_INTERRUPT  6
#define PRIORITY_INTERVAL_INTERRUPT 6
#define PRIORITY_VBLANK_INTERRUPT   6

enum TaleaInterrupt {
    EXCEPTION_RESET,
    EXCEPTION_BUS_ERROR = 0x2,
    EXCEPTION_ADDRESS_ERROR,
    EXCEPTION_ILLEGAL_INSTRUCTION,
    EXCEPTION_DIVISION_ZERO,
    EXCEPTION_PRIVILEGE_VIOLATION,
    EXCEPTION_PAGE_FAULT,
    EXCEPTION_ACCESS_VIOLATION,

    INT_TTY_TRANSMIT = 0xA,
    INT_KBD_CHAR,
    INT_KBD_SCAN,
    INT_TPS_FINISH,
    INT_HCS_FINISH,
    INT_TIMER_TIMEOUT,
    INT_TIMER_INTERVAL,
    INT_VIDEO_REFRESH,
    INT_MOUSE_PRESSED,
    INT_TPS_EJECTED,
    INT_TPS_INSERTED,
    INT_AUDIO0_NOTE_END,
    INT_AUDIO1_NOTE_END,
    INT_AUDIO2_NOTE_END,
    INT_AUDIO3_NOTE_END
};


#endif /* INTERRUPTS_H */
