(= push (mac (val lst)
  (list '= lst (list 'cons val lst))
))


(= for (mac (item lst . body)
  (let for-iter (gensym))
  (list 'do
    (list 'let for-iter lst)
    (list 'while for-iter
      (list 'let item (list 'car for-iter))
      (list '= for-iter (list 'cdr for-iter))
      (cons 'do body)
    )
  )
))


(= items (list "cat" "dog" "fox"))

(push "owl" items)
(push "cow" items)

(for x items
  (print ">" x)
)
