#ifndef INTERRUPTS_H
#define INTERRUPTS_H

/* @AKAI: 800_PRIORITIES */
#define PRIORITY_KEYBOARD_INTERRUPT 4
#define PRIORITY_SERIAL_INTERRUPT   5
#define PRIORITY_STORAGE_INTERRUPT  5
#define PRIORITY_AUDIO_INTERRUPT    2
#define PRIORITY_TIMEOUT_INTERRUPT  6
#define PRIORITY_INTERVAL_INTERRUPT 6
#define PRIORITY_VBLANK_INTERRUPT   6
/* @AKAI */

#endif /* INTERRUPTS_H */
